### ISSUE TITLE
AsyncAware::ThreadTimedOut (The thread ... did not complete within 10 seconds.)

### ISSUE THREAD

**Issue by jakubzitny** [openshift/origin-server#5760]
Hi,

I installed openshift with broker and everything else on a virtual server with 1G RAM and everything was running okay, but little bit slow. So I restarted the vm an gave it 4 cores and 4G but after loading console in browser it fails on following timeout.

```
2014-08-26 23:46:27.392 [ERROR] AsyncAware::ThreadTimedOut (The thread #<Thread:0x00000004d42b60 aborting> (index=1) did not complete within 10 seconds.) (pid:3316)
2014-08-26 23:46:27.393 [ERROR] Unhandled exception reference #331288ffe8ba7764812d26d864a99029: Failed.  Response code = 500.  Response message = Internal Server Error.
/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.26.3.1/lib/active_resource/persistent_connection.rb:218:in `handle_response'
  /opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.26.3.1/lib/active_resource/persistent_connection.rb:175:in `request'
  /opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.26.3.1/lib/active_resource/persistent_connection.rb:112:in `block in get'
  /opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.26.3.1/lib/active_resource/persistent_connection.rb:284:in `with_auth'
  /opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.26.3.1/lib/active_resource/persistent_connection.rb:112:in `get'
  /opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.26.3.1/app/models/rest_api/base.rb:820:in `find_every'
  /opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.26.3.1/app/models/rest_api/base.rb:473:in `find'
  /opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.26.3.1/app/models/application.rb:56:in `find'
  /opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.26.3.1/app/controllers/applications_controller.rb:83:in `block in index'
  /opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.26.3.1/app/controllers/async_aware.rb:14:in `block in async' (pid:3316)
```

Is there any possibility to increase the timeout or make the execution faster without moving db, mq and broker onto different servers? The fact that it is THIS slow should not be affected mainly by having everything on one machine, right? Are there any ways to speed things (the broker, httpd, ...) up?

Thanks.

**Comment by tiwillia** [comment]
@danmcp we can close this out.
