### ISSUE TITLE
Unable to create jenkins server app after oo-install on Centos 6.5 host

### ISSUE THREAD

**Issue by tiwillia** [openshift/origin-server#6193]
On a freshly installed Centos-6.5 host where oo-install was used to create an all-in-one environment, a jenkins app cannot be created:
```
Creating application 'jenkins' ... 
Starting jenkins cartridge
Timed out waiting for Jenkins to fully start
Failed to execute: 'control start' for /var/lib/openshift/559ea385a4ffcfe0360000c8/jenkins
```

The error reported in the jenkins logs pertains to the version of openjdk installed:
```
Jenkins requires Java7 or later, but you are running 1.6.0_35-b35 from /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre
java.lang.UnsupportedClassVersionError: 50.0
	at Main.main(Main.java:90)
```

The `http://pkg.jenkins-ci.org/redhat/` repo used by oo-install + CentOS contains versions of jenkins greater than 1.614, where a [change was made to require java7](http://jenkins-ci.org/content/good-bye-java6).

Installing `java-1.7.0-openjdk` resolves the issue. Perhaps the jenkins cartridge should now be requiring jdk7?

**Comment by tiwillia** [comment]
The `http://pkg.jenkins-ci.org/redhat/` repo used by oo-install + CentOS contains versions of jenkins greater than 1.614, where a [change was made to require java7](http://jenkins-ci.org/content/good-bye-java6).

This issue is not reproducible in enterprise since `jenkins-1.565` is the latest version provided.

**Comment by infosatheesh2020** [comment]
Hi, I'm getting below error in CentOS 6:

Jenkins requires Java7 or later, but you are running 1.7.0_141-mockbuild_2017_05_09_14_20-b00 from /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.141.x86_64/jre
java.lang.UnsupportedClassVersionError: winstone/Launcher : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at Main._main(Main.java:224)
        at Main.main(Main.java:112)

What is wrong here since it already uses Java7?

**Comment by Niyojan** [comment]
Same issue here: 

> Running from: /usr/lib/jenkins/jenkins.war
May 23, 2017 11:25:20 PM Main deleteWinstoneTempContents
WARNING: Failed to delete the temporary Winstone file /tmp/winstone/jenkins.war
Jenkins requires Java7 or later, but you are running 1.7.0_131-mockbuild_2017_02_15_02_03-b00 from /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.131.x86_64/jre
java.lang.UnsupportedClassVersionError: winstone/Launcher : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at Main._main(Main.java:224)
        at Main.main(Main.java:112)

**Comment by RandyMeyer** [comment]
same thing here too:

```
Running from: /usr/lib/jenkins/jenkins.war
Jun 15, 2017 6:37:27 PM Main deleteWinstoneTempContents
WARNING: Failed to delete the temporary Winstone file /tmp/winstone/jenkins.war
Jenkins requires Java7 or later, but you are running 1.7.0_141-mockbuild_2017_06_03_00_52-b00 from /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.141.x86_64/jre
java.lang.UnsupportedClassVersionError: winstone/Launcher : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at Main._main(Main.java:224)
	at Main.main(Main.java:112)
```

**Comment by infosatheesh2020** [comment]
When I upgrade to Java 8, it was working for me
